### ISSUE TITLE
Cryptic Install error

### ISSUE THREAD

**Issue by curtisko** [ygjb/kitherder#4]
(kit)curtis@U2:~/kitherder-master/kitherder$ python manage.py syncdb
Error: cannot import name six

**Comment by curtisko** [comment]
No, that is all I get

## 

Curtis Koenig
(m) (502)510-1976

**Comment by wiredcrow** [comment]
hi curtis, can you check your version of django? i believe this error comes up due to different versions. I had coded using Django 1.3.1

**Comment by curtisko** [comment]
(kit)curtis@U2:~/kitherder-master/kitherder$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import django
> > > django.VERSION
> > > (1, 3, 1, 'final', 0)

**Comment by wiredcrow** [comment]
My apologies. At some point, someone had upgraded the codebase to require "six" as a django package. Looks like a refresh install now requires django 1.4.  (Seehttps://github.com/ygjb/kitherder/blob/master/kitherder/requirements.txt). I will go update the documentation accordingly.

**Comment by curtisko** [comment]
so I need to upgrade from 1.3.1 to 1.4 ?

**Comment by wiredcrow** [comment]
Yes please. It should resolve the problem

**Comment by curtisko** [comment]
(kit)curtis@U2:~/kitherder-master/kitherder$ python manage.py syncdb
Error: cannot import name six
(kit)curtis@U2:~/kitherder-master/kitherder$ pip install six==1.5.2
Requirement already satisfied (use --upgrade to upgrade): six==1.5.2 in /home/curtis/kit/lib/python2.7/site-packages
Cleaning up...
(kit)curtis@U2:~/kitherder-master/kitherder$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import django
> > > django.VERSION
> > > (1, 4, 0, 'final', 0)

**Comment by wiredcrow** [comment]
apparently the documentation sunu left is also missing something. According to this: https://github.com/django-mptt/django-mptt/issues/271 and http://stackoverflow.com/questions/16100454/no-module-named-six,  it requires 1.4.2 or greater. Apologies as this is new to me as well.

**Comment by curtisko** [comment]
ok, that part worked but now I have this problem
line 151:SITE_URL = 'http://127.0.0.1:6000'

(kit)curtis@U2:~/kitherder-master/kitherder$ python manage.py runserver
Validating models...

0 errors found
Django version 1.4.2, using settings 'kitherder.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
(kit)curtis@U2:~/kitherder-master/kitherder$

**Comment by curtisko** [comment]
I already have mozillians running on 127.0.0.1:8000 by the way

**Comment by wiredcrow** [comment]
Try the command python manage.py runserver 6000

**Comment by curtisko** [comment]
I moved it to 8080
http://127.0.0.1:8080  yeilds
ImportError at /

cannot import name is_safe_url

Request Method:     GET
Request URL:    http://127.0.0.1:8080/
Django Version:     1.4.2
Exception Type:     ImportError
Exception Value:    

cannot import name is_safe_url

Exception Location:     /home/curtis/kit/local/lib/python2.7/site-packages/django_browserid/views.py in <module>, line 11
Python Executable:  /home/curtis/kit/bin/python
Python Version:     2.7.6
Python Path:    

['/home/curtis/kitherder-master/kitherder',
 '/home/curtis/kit/lib/python2.7',
 '/home/curtis/kit/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/curtis/kit/lib/python2.7/lib-tk',
 '/home/curtis/kit/lib/python2.7/lib-old',
 '/home/curtis/kit/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/curtis/kit/local/lib/python2.7/site-packages',
 '/home/curtis/kit/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info',
 '/home/curtis/kit/lib/python2.7/site-packages',
 '/home/curtis/kit/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info']

Server time:    Fri, 17 Oct 2014 15:07:20 -0700

**Comment by wiredcrow** [comment]
Ah, another name error..unfortunately it looks like now it's version 1.4.3+. (https://bugs.launchpad.net/devstack/+bug/1154391)

**Comment by curtisko** [comment]
pip uninstall djago > success
pip install django==1.4.3 > success
python manage.py runserver 8080 > success
reload 
ImportError at /

cannot import name verify

Request Method:     GET
Request URL:    http://127.0.0.1:8080/
Django Version:     1.4.3
Exception Type:     ImportError
Exception Value:    

cannot import name verify

Exception Location:     /home/curtis/kitherder-master/kitherder/entrance/views.py in <module>, line 11
Python Executable:  /home/curtis/kit/bin/python
Python Version:     2.7.6
Python Path:    

['/home/curtis/kitherder-master/kitherder',
 '/home/curtis/kit/lib/python2.7',
 '/home/curtis/kit/lib/python2.7/plat-x86_64-linux-gnu',
 '/home/curtis/kit/lib/python2.7/lib-tk',
 '/home/curtis/kit/lib/python2.7/lib-old',
 '/home/curtis/kit/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/home/curtis/kit/local/lib/python2.7/site-packages',
 '/home/curtis/kit/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info',
 '/home/curtis/kit/lib/python2.7/site-packages',
 '/home/curtis/kit/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info']

Server time:    Fri, 17 Oct 2014 15:28:50 -0700

**Comment by wiredcrow** [comment]
Did you install browserid (persona)?
http://django-browserid.readthedocs.org/en/latest/user/quickstart.html

**Comment by curtisko** [comment]
yes

**Comment by wiredcrow** [comment]
Ah, looks like with the 0.11 release, verify had changed (http://django-browserid.readthedocs.org/en/latest/search.html?q=verify&check_keywords=yes&area=default#). I was using 0.9 when I was doing development in the summer. 

Any way to proceed ahead with the browserid 0.9? If not, I'll have to do a bunch of dev to make it work with 0.11. (Unfortunately not something I can get into right now)

**Comment by curtisko** [comment]
pip uninstall django-broswerid > success
pip install django-browserid==0.9 success
(kit)curtis@U2:~/kitherder-master/kitherder$ python manage.py runserver 8080
Validating models...

0 errors found
Django version 1.4.4, using settings 'kitherder.settings'
Development server is running at http://127.0.0.1:8080/
Quit the server with CONTROL-C.

reload page > SUCCESS

only issue images look like they are missing, and I have to find where to log in

also not sure where to use my api key, got one, but don't know where to use it

**Comment by wiredcrow** [comment]
Excellent yay! Let me know if you want me to take a look.

The API key is unfortunately embedded right now. If you send it to me, I can do some modifications tonight and push out a new build tomorrow. Come to think of it, I should create a private file for the api key to be stored in and pointed to so that the API key is not exposed in the source code in the repo.

**Comment by curtisko** [comment]
I noticed the instructions said to have one, this the confusion.

On Friday, October 17, 2014, wiredcrow notifications@github.com wrote:

> Excellent yay! Let me know if you want me to take a look.
> 
> The API key is unfortunately embedded right now. If you send it to me, I
> can do some modifications tonight and push out a new build tomorrow. Come
> to think of it, I should create a private file for the api key to be stored
> in and pointed to so that the API key is not exposed in the source code in
> the repo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ygjb/kitherder/issues/4#issuecomment-59587505.

## 

## 

Curtis Koenig
(m) (502)510-1976

**Comment by curtisko** [comment]
logged in and went to register and I get this error:

Kitherder cannot reach Mozillian and cannot verify if you are vouched in Mozillian. Please try again later. (You must be vouched in Mozillian to be a mentor.) 

I should probably modify the code to point to my local mozillians instance instead of the real instance so I can use my generated app key in an environment I have full control of.

**Comment by wiredcrow** [comment]
Let me do some work tonight to allow for different api keys to be used
depending on instance. I'll update the information on how to insert api key
in.

**Comment by wiredcrow** [comment]
Okay, code has been updated.

In your settings file, add these two lines at the very bottom of the file:

MOZILLIAN_URL = 'http://192.81.128.7:8000'
MOZILLIAN_APP_KEY = '12345'

Replace the URL and the app key with your key and the url of the local Mozillian.

That should work, log a separate bug if anything fails

**Comment by curtisko** [comment]
This seems to be working great, I am looged in, and verified as a mentor. Now to figure out why many of the images are giving me a 404 from the static dir, I'll file a seperate bug for that.
